server:
  port: 8080

spring:
  application:
    name: mes-poc
  datasource:
    url: jdbc:h2:mem:mesdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# OPC-UA Configuration
opcua:
  endpoint: ${OPCUA_ENDPOINT:opc.tcp://localhost:4840}
  security-policy: "None"
  message-security-mode: "None"
  application-name: "MES-Poc-Client"
  application-uri: "urn:mes:poc:client"
  product-uri: "urn:mes:core:product"
  request-timeout: 5000
  session-timeout: 60000
  subscription-publishing-interval: 1000.0
  nodes:
    - nodeId: "ns=2;i=1001"
      name: "Temperature"
      dataType: "DOUBLE"
    - nodeId: "ns=2;i=1002"
      name: "Pressure"
      dataType: "DOUBLE"
    - nodeId: "ns=2;i=1003"
      name: "EquipmentStatus"
      dataType: "STRING"
    - nodeId: "ns=2;i=1004"
      name: "ProductionCount"
      dataType: "INTEGER"

# Scheduling Configuration
scheduler:
  data-collection:
    enabled: true
    fixed-rate: 5000  # 5 seconds
  alarm-check:
    enabled: true
    fixed-rate: 10000  # 10 seconds

# Logging
logging:
  level:
    com.mes.poc: DEBUG
    org.eclipse.milo: INFO
    org.springframework: INFO