# application-docker.yml
spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/mesdb
    username: ${DB_USERNAME:mes_user}
    password: ${DB_PASSWORD:mes_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

opcua:
  endpoint: ${OPCUA_ENDPOINT:opc.tcp://opcua-server:4840}
  request-timeout: 10000
  session-timeout: 120000

logging:
  level:
    com.example.mescore: INFO
    org.eclipse.milo: WARN
  file:
    name: logs/mes-core-docker.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  server:
    port: 8081